common:
    arch: vgg11_bn
    workers: 4
    batch_size: 128
    epochs: 20
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/vgg11_bn_CIFAR100
    use_gpu: True
    dataset: CIFAR100
    every_decay: 5
